### ISSUE TITLE
add support for WinUI 3

### ISSUE THREAD

**Issue by nepton** [levitali/CompiledBindings#18]
Could you add support for WinUI 3?
Thanks :)

**Comment by levitali** [comment]
Yes, it's possible. I've uploaded a betta CompiledBindings.WinUI nuget.

There is one difference to XF/MAU/WPF. Because in WinUI there is already the x:Bind extension, as well as there is no XmlnsDefinitionAttribute to map the CompiledBindings.Markup to x Namespace, you have to declare explicitly the CLR namespace with some prefix. For example:
 ```xaml
xmlns:c="using:CompiledBindings.Markup"

 <TextBlock Text="{c:Bind Prop1}" />
 ```

The other possibilities, like using m: Namespace for properties work.

**Comment by cesarchefinho** [comment]
dos this work with uno (winui version of uno, of course) ?

**Comment by levitali** [comment]
I've never tried it.
